/*
 * 
 * ProductDiscountBaseDPanel.java
 *
 * Created on 28 Март 2008 г., 12:06
 */
package tradeterminal.operations.products.selling.p0.dialogs.base;

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.text.ParseException;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import minersinstrument.ui.IADialogPanel;
import org.jdesktop.application.Action;

/**
 *
 * @author  PKopychenko
 */
public abstract class ProductDiscountBaseDPanel extends javax.swing.JPanel implements IADialogPanel {

    protected double list_price = 0;
    protected double maximum = 0;
    protected double minimum = 0;
    
    private double min(double a , double b){
        return a < b ? a : b;
    }
    private double max(double a , double b){
        return a > b ? a : b;
    }
    

    /** Creates new form ProductDiscountBaseDPanel */
    public ProductDiscountBaseDPanel(double list_price, double value, double minimum0, double maximum0, double stepSize) {
        initComponents();

        this.list_price = list_price;
        list_priceFormattedTextField.setValue(list_price);

        this.maximum = max(maximum0, minimum0);
        this.minimum = min(maximum0, minimum0);

        SpinnerNumberModel sm = new SpinnerNumberModel(
                Double.valueOf(value),
                Double.valueOf(minimum),
                Double.valueOf(maximum),
                Double.valueOf(stepSize));

        valueSpinner.setModel(sm);

        minButton.setText(Double.toString(minimum));
        maxButton.setText(Double.toString(maximum));

        valueSlider.setMinimum(new BigDecimal(Math.round(minimum)).intValue());
        valueSlider.setMaximum(new BigDecimal(Math.round(maximum)).intValue());

        final DefaultEditor de = (DefaultEditor) valueSpinner.getEditor();

        de.getTextField().addCaretListener(new javax.swing.event.CaretListener() {

            @Override
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                try {
                    NumberFormat nf = java.text.DecimalFormat.getInstance();
                    valueSlider.setValue(new BigDecimal(Math.round(nf.parse(de.getTextField().getText()).doubleValue())).intValue());
                    calculate();
                } catch (Exception ex) {
                }
            }
        });

        valueSlider.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                if (valueSlider.isFocusOwner()) {
                    valueSpinner.setValue((double) valueSlider.getValue());
                    calculate();
                }
            }
        });

        valueSpinner.setValue(value);
        valueSlider.setValue(new BigDecimal(Math.round(value)).intValue());
        calculate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        prefixLabel = new javax.swing.JLabel();
        valueSpinner = new javax.swing.JSpinner();
        suffixLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        valueSlider = new javax.swing.JSlider();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        discontPriceFormattedTextField = new javax.swing.JFormattedTextField();
        minButton = new javax.swing.JButton();
        maxButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        list_priceFormattedTextField = new javax.swing.JFormattedTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout(5, 5));

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getResourceMap(ProductDiscountBaseDPanel.class);
        prefixLabel.setText(resourceMap.getString("prefixLabel.text")); // NOI18N
        prefixLabel.setName("prefixLabel"); // NOI18N

        valueSpinner.setFont(resourceMap.getFont("valueSpinner.font")); // NOI18N
        valueSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.0f), Float.valueOf(101.0f), Float.valueOf(0.1f)));
        valueSpinner.setName("valueSpinner"); // NOI18N
        valueSpinner.setPreferredSize(new java.awt.Dimension(80, 18));

        suffixLabel.setText(resourceMap.getString("suffixLabel.text")); // NOI18N
        suffixLabel.setName("suffixLabel"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(prefixLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suffixLabel)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suffixLabel)
                    .addComponent(prefixLabel)))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout(5, 5));

        valueSlider.setMajorTickSpacing(10);
        valueSlider.setMinorTickSpacing(1);
        valueSlider.setPaintLabels(true);
        valueSlider.setPaintTicks(true);
        valueSlider.setSnapToTicks(true);
        valueSlider.setMinimumSize(new java.awt.Dimension(200, 46));
        valueSlider.setName("valueSlider"); // NOI18N
        jPanel2.add(valueSlider, java.awt.BorderLayout.CENTER);

        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(180, 14));
        jPanel7.add(jLabel7, java.awt.BorderLayout.LINE_START);

        discontPriceFormattedTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        discontPriceFormattedTextField.setEditable(false);
        discontPriceFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        discontPriceFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discontPriceFormattedTextField.setFont(resourceMap.getFont("discontPriceFormattedTextField.font")); // NOI18N
        discontPriceFormattedTextField.setName("discontPriceFormattedTextField"); // NOI18N
        discontPriceFormattedTextField.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel7.add(discontPriceFormattedTextField, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getActionMap(ProductDiscountBaseDPanel.class, this);
        minButton.setAction(actionMap.get("setMin")); // NOI18N
        minButton.setText(resourceMap.getString("minButton.text")); // NOI18N
        minButton.setName("minButton"); // NOI18N
        jPanel2.add(minButton, java.awt.BorderLayout.LINE_START);

        maxButton.setAction(actionMap.get("setMax")); // NOI18N
        maxButton.setText(resourceMap.getString("maxButton.text")); // NOI18N
        maxButton.setName("maxButton"); // NOI18N
        jPanel2.add(maxButton, java.awt.BorderLayout.LINE_END);

        add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 14));
        jPanel3.add(jLabel1, java.awt.BorderLayout.WEST);

        list_priceFormattedTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        list_priceFormattedTextField.setEditable(false);
        list_priceFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        list_priceFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        list_priceFormattedTextField.setFont(resourceMap.getFont("list_priceFormattedTextField.font")); // NOI18N
        list_priceFormattedTextField.setName("list_priceFormattedTextField"); // NOI18N
        list_priceFormattedTextField.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel3.add(list_priceFormattedTextField, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    public void setCurency(String s) {
    }

    public void setSuffixText(String s) {
        suffixLabel.setText(s);
        minButton.setText(Double.toString(minimum) + s);
        maxButton.setText(Double.toString(maximum) + s);
    }

    abstract public void calculate();

    @Override
    public boolean checkPanel() {
        try {
            valueSpinner.commitEdit();

            return true;
        } catch (ParseException ex) {
            return false;
        }
    }

    @Override
    public void openPanel() {
    }

    public double getDiscountValue() {
        return (Double) valueSpinner.getValue();
    }

    @Action
    public void setMin() {
        valueSpinner.setValue(minimum);
        
        
        calculate();
    }

    @Action
    public void setMax() {
        valueSpinner.setValue(maximum);
        
        
        
        calculate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JFormattedTextField discontPriceFormattedTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    protected javax.swing.JFormattedTextField list_priceFormattedTextField;
    private javax.swing.JButton maxButton;
    private javax.swing.JButton minButton;
    protected javax.swing.JLabel prefixLabel;
    protected javax.swing.JLabel suffixLabel;
    protected javax.swing.JSlider valueSlider;
    protected javax.swing.JSpinner valueSpinner;
    // End of variables declaration//GEN-END:variables
}
