/*
 * MoneyOperationQueryPanel.java
 *
 * Created on 3 Март 2008 г., 21:19
 */
package tradeterminal.operations.products.ppl_psl_files_history_info;

import java.util.Date;
import minersinstrument.ui.IADialogPanel;

/**
 *
 * @author  kopychenko
 */
public final class SelectDPanel extends javax.swing.JPanel implements IADialogPanel {

    
    
    /** Creates new form MoneyOperationQueryPanel */
    public SelectDPanel() {
        initComponents();

        beginDatePicker.setDate(new Date());
        endDatePicker.setDate(new Date((new Date()).getTime() + 24 * 60 * 60 * 1000));
    }

    
    
    
    public boolean isAllSelected() {
        return selectAllCheckBox.isSelected();
    }

    public boolean isfindFiles() {
        return findFilesCheckBox.isSelected();
    }

    public String getFileName() {
        return fileNameTextField.getText();
    }

    public int getFileOrderId() {
        return (Integer) fileOrderIdSpinner.getValue();
    }

    public boolean isSelectForDate() {
        return selectForDateCheckBox.isSelected();
    }

    public Date getBegin() {
        return beginDatePicker.getDate();
    }

    public void setBeginDate(Date d) {
        this.beginDatePicker.setDate(d);
    }

    public Date getEndDate() {
        return endDatePicker.getDate();
    }

    public void setEndDate(Date d) {
        this.endDatePicker.setDate(d);
    }

    public boolean isForOperationTypeCode() {
        return forOperationTypeCodeCheckBox.isSelected();
    }

    public String getOperationTypeCode() {
        if (pslRadioButton.isSelected()) {
            return "psl";
        } else {
            return "ppl";
        }
    }

    public boolean isIsCreatedBackFile() {
        return isCreatedBackFileCheckBox.isSelected();
    }

    public String getBackFileName() {
        return backFileNameTextField.getText();
    }

    @Override
    public boolean checkPanel() {
        return true;
    }

    @Override
    public void openPanel() {
        beginDatePicker.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        beginDatePicker = new org.jdesktop.swingx.JXDatePicker();
        endDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectAllCheckBox = new javax.swing.JCheckBox();
        findFilesCheckBox = new javax.swing.JCheckBox();
        selectForDateCheckBox = new javax.swing.JCheckBox();
        forOperationTypeCodeCheckBox = new javax.swing.JCheckBox();
        isCreatedBackFileCheckBox = new javax.swing.JCheckBox();
        fileNameTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fileOrderIdSpinner = new javax.swing.JSpinner();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        pslRadioButton = new javax.swing.JRadioButton();
        pplRadioButton = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        backFileNameTextField = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        beginDatePicker.setEnabled(false);
        beginDatePicker.setName("beginDatePicker"); // NOI18N
        beginDatePicker.setPreferredSize(new java.awt.Dimension(0, 28));

        endDatePicker.setEnabled(false);
        endDatePicker.setName("endDatePicker"); // NOI18N
        endDatePicker.setPreferredSize(new java.awt.Dimension(0, 28));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getResourceMap(SelectDPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setEnabled(false);
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setEnabled(false);
        jLabel2.setName("jLabel2"); // NOI18N

        selectAllCheckBox.setText(resourceMap.getString("selectAllCheckBox.text")); // NOI18N
        selectAllCheckBox.setName("selectAllCheckBox"); // NOI18N
        selectAllCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllCheckBoxActionPerformed(evt);
            }
        });

        findFilesCheckBox.setText(resourceMap.getString("findFilesCheckBox.text")); // NOI18N
        findFilesCheckBox.setName("findFilesCheckBox"); // NOI18N
        findFilesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findFilesCheckBoxActionPerformed(evt);
            }
        });

        selectForDateCheckBox.setText(resourceMap.getString("selectForDateCheckBox.text")); // NOI18N
        selectForDateCheckBox.setName("selectForDateCheckBox"); // NOI18N
        selectForDateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectForDateCheckBoxActionPerformed(evt);
            }
        });

        forOperationTypeCodeCheckBox.setText(resourceMap.getString("forOperationTypeCodeCheckBox.text")); // NOI18N
        forOperationTypeCodeCheckBox.setName("forOperationTypeCodeCheckBox"); // NOI18N
        forOperationTypeCodeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forOperationTypeCodeCheckBoxActionPerformed(evt);
            }
        });

        isCreatedBackFileCheckBox.setText(resourceMap.getString("isCreatedBackFileCheckBox.text")); // NOI18N
        isCreatedBackFileCheckBox.setName("isCreatedBackFileCheckBox"); // NOI18N
        isCreatedBackFileCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isCreatedBackFileCheckBoxActionPerformed(evt);
            }
        });

        fileNameTextField.setText(resourceMap.getString("fileNameTextField.text")); // NOI18N
        fileNameTextField.setEnabled(false);
        fileNameTextField.setName("fileNameTextField"); // NOI18N
        fileNameTextField.setPreferredSize(new java.awt.Dimension(0, 28));

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setEnabled(false);
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setEnabled(false);
        jLabel4.setName("jLabel4"); // NOI18N

        fileOrderIdSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        fileOrderIdSpinner.setEnabled(false);
        fileOrderIdSpinner.setName("fileOrderIdSpinner"); // NOI18N
        fileOrderIdSpinner.setPreferredSize(new java.awt.Dimension(0, 28));

        jSeparator2.setName("jSeparator2"); // NOI18N

        jSeparator3.setName("jSeparator3"); // NOI18N

        buttonGroup1.add(pslRadioButton);
        pslRadioButton.setText(resourceMap.getString("pslRadioButton.text")); // NOI18N
        pslRadioButton.setEnabled(false);
        pslRadioButton.setName("pslRadioButton"); // NOI18N

        buttonGroup1.add(pplRadioButton);
        pplRadioButton.setSelected(true);
        pplRadioButton.setText(resourceMap.getString("pplRadioButton.text")); // NOI18N
        pplRadioButton.setEnabled(false);
        pplRadioButton.setName("pplRadioButton"); // NOI18N

        jSeparator4.setName("jSeparator4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setEnabled(false);
        jLabel5.setName("jLabel5"); // NOI18N

        backFileNameTextField.setEnabled(false);
        backFileNameTextField.setName("backFileNameTextField"); // NOI18N
        backFileNameTextField.setPreferredSize(new java.awt.Dimension(0, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectAllCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(findFilesCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addComponent(fileOrderIdSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectForDateCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beginDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(forOperationTypeCodeCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(pslRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pplRadioButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(isCreatedBackFileCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(backFileNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectAllCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(findFilesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fileOrderIdSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectForDateCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beginDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forOperationTypeCodeCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pslRadioButton)
                    .addComponent(pplRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isCreatedBackFileCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backFileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectAllCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllCheckBoxActionPerformed
        boolean e = !selectAllCheckBox.isSelected();

        fileNameTextField.setEnabled(e);
        backFileNameTextField.setEnabled(e);

        fileOrderIdSpinner.setEnabled(e);

        pslRadioButton.setEnabled(e);
        pplRadioButton.setEnabled(e);

        findFilesCheckBox.setEnabled(e);
        selectForDateCheckBox.setEnabled(e);
        forOperationTypeCodeCheckBox.setEnabled(e);
        isCreatedBackFileCheckBox.setEnabled(e);

        beginDatePicker.setEnabled(e);
        endDatePicker.setEnabled(e);

        jLabel1.setEnabled(e);
        jLabel2.setEnabled(e);
        jLabel3.setEnabled(e);
        jLabel4.setEnabled(e);
        jLabel5.setEnabled(e);
    }//GEN-LAST:event_selectAllCheckBoxActionPerformed

    private void findFilesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findFilesCheckBoxActionPerformed
        boolean e = findFilesCheckBox.isSelected();
        fileNameTextField.setEnabled(e);
        fileOrderIdSpinner.setEnabled(e);
        jLabel3.setEnabled(e);
        jLabel4.setEnabled(e);
    }//GEN-LAST:event_findFilesCheckBoxActionPerformed

    private void selectForDateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectForDateCheckBoxActionPerformed
        boolean e = selectForDateCheckBox.isSelected();
        jLabel1.setEnabled(e);
        jLabel2.setEnabled(e);
        beginDatePicker.setEnabled(e);
        endDatePicker.setEnabled(e);
    }//GEN-LAST:event_selectForDateCheckBoxActionPerformed

    private void forOperationTypeCodeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forOperationTypeCodeCheckBoxActionPerformed
        boolean e = forOperationTypeCodeCheckBox.isSelected();
        pslRadioButton.setEnabled(e);
        pplRadioButton.setEnabled(e);
    }//GEN-LAST:event_forOperationTypeCodeCheckBoxActionPerformed

    private void isCreatedBackFileCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isCreatedBackFileCheckBoxActionPerformed
        boolean e = isCreatedBackFileCheckBox.isSelected();
        jLabel5.setEnabled(e);
        backFileNameTextField.setEnabled(e);
    }//GEN-LAST:event_isCreatedBackFileCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField backFileNameTextField;
    private org.jdesktop.swingx.JXDatePicker beginDatePicker;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdesktop.swingx.JXDatePicker endDatePicker;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JSpinner fileOrderIdSpinner;
    private javax.swing.JCheckBox findFilesCheckBox;
    private javax.swing.JCheckBox forOperationTypeCodeCheckBox;
    private javax.swing.JCheckBox isCreatedBackFileCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton pplRadioButton;
    private javax.swing.JRadioButton pslRadioButton;
    private javax.swing.JCheckBox selectAllCheckBox;
    private javax.swing.JCheckBox selectForDateCheckBox;
    // End of variables declaration//GEN-END:variables
}
