/*
 * FirstPanel.java
 *
 * Created on 19 Ноябрь 2008 г., 22:57
 */
package tradeterminal;

import java.util.List;
import javax.swing.Icon;
import javax.swing.JMenuItem;
import tradeterminal.conf.AppAccessSettings;

/**
 *
 * @author  pacman
 */


/**
 * 
 * @author peresypkinmax    
 */
public final class FirstPanel extends javax.swing.JPanel implements IPage {

    private MainForm mainForm;

    /** Creates new form FirstPanel */
    public FirstPanel(MainForm mainForm) {
        initComponents();

        this.mainForm = mainForm;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selProductButton = new javax.swing.JButton();
        addMoneyToCassButton = new javax.swing.JButton();
        returnProductButton = new javax.swing.JButton();
        addProductButton = new javax.swing.JButton();
        showCassButton = new javax.swing.JButton();
        removeProductButton = new javax.swing.JButton();
        addMoneyToBalanceButton = new javax.swing.JButton();
        removeMoneyFromCassButton = new javax.swing.JButton();
        removeMoneyFromBalanceButton = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 3, 3));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getResourceMap(FirstPanel.class);
        selProductButton.setIcon(resourceMap.getIcon("selProductButton.icon")); // NOI18N
        selProductButton.setText(resourceMap.getString("selProductButton.text")); // NOI18N
        selProductButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selProductButton.setName("selProductButton"); // NOI18N
        selProductButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selProductButtonActionPerformed(evt);
            }
        });
        jPanel1.add(selProductButton);

        addMoneyToCassButton.setIcon(resourceMap.getIcon("addMoneyButton.icon")); // NOI18N
        addMoneyToCassButton.setText(resourceMap.getString("addMoneyButton.text")); // NOI18N
        addMoneyToCassButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addMoneyToCassButton.setName("addMoneyButton"); // NOI18N
        addMoneyToCassButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addMoneyToCassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoneyToCassButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addMoneyToCassButton);

        returnProductButton.setIcon(resourceMap.getIcon("returnProductButton.icon")); // NOI18N
        returnProductButton.setText(resourceMap.getString("returnProductButton.text")); // NOI18N
        returnProductButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        returnProductButton.setName("returnProductButton"); // NOI18N
        returnProductButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        returnProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnProductButtonActionPerformed(evt);
            }
        });
        jPanel1.add(returnProductButton);

        addProductButton.setIcon(resourceMap.getIcon("addProductButton.icon")); // NOI18N
        addProductButton.setText(resourceMap.getString("addProductButton.text")); // NOI18N
        addProductButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addProductButton.setName("addProductButton"); // NOI18N
        addProductButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addProductButton);

        showCassButton.setIcon(resourceMap.getIcon("showCassButton.icon")); // NOI18N
        showCassButton.setText(resourceMap.getString("showCassButton.text")); // NOI18N
        showCassButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showCassButton.setName("showCassButton"); // NOI18N
        showCassButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        showCassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCassButtonActionPerformed(evt);
            }
        });
        jPanel1.add(showCassButton);

        removeProductButton.setIcon(resourceMap.getIcon("removeProductButton.icon")); // NOI18N
        removeProductButton.setText(resourceMap.getString("removeProductButton.text")); // NOI18N
        removeProductButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeProductButton.setName("removeProductButton"); // NOI18N
        removeProductButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProductButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeProductButton);

        addMoneyToBalanceButton.setIcon(resourceMap.getIcon("addMoneyToBalanceButton.icon")); // NOI18N
        addMoneyToBalanceButton.setText(resourceMap.getString("addMoneyToBalanceButton.text")); // NOI18N
        addMoneyToBalanceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addMoneyToBalanceButton.setName("addMoneyToBalanceButton"); // NOI18N
        addMoneyToBalanceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addMoneyToBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoneyToBalanceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addMoneyToBalanceButton);

        removeMoneyFromCassButton.setIcon(resourceMap.getIcon("removeMoneyFromBalanceButton.icon")); // NOI18N
        removeMoneyFromCassButton.setText(resourceMap.getString("removeMoneyFromBalanceButton.text")); // NOI18N
        removeMoneyFromCassButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeMoneyFromCassButton.setName("removeMoneyFromBalanceButton"); // NOI18N
        removeMoneyFromCassButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeMoneyFromCassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMoneyFromCassButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeMoneyFromCassButton);

        removeMoneyFromBalanceButton.setIcon(resourceMap.getIcon("removeMoneyButton.icon")); // NOI18N
        removeMoneyFromBalanceButton.setText(resourceMap.getString("removeMoneyButton.text")); // NOI18N
        removeMoneyFromBalanceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeMoneyFromBalanceButton.setName("removeMoneyButton"); // NOI18N
        removeMoneyFromBalanceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeMoneyFromBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMoneyFromBalanceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeMoneyFromBalanceButton);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void selProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selProductButtonActionPerformed

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.SELLING_PRODUCT)) {
            return;
        }

        mainForm.showPanel("ProductsSellingMainPanel");
    }//GEN-LAST:event_selProductButtonActionPerformed

    private void addMoneyToCassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoneyToCassButtonActionPerformed

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.ADD_MONEY)) {
            return;
        }

        mainForm.addMoneyToCass();
    }//GEN-LAST:event_addMoneyToCassButtonActionPerformed

    private void returnProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnProductButtonActionPerformed

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.RETURN_PRODUCT)) {
            return;
        }

        mainForm.showPanel("ReturnProductMainPanel");
    }//GEN-LAST:event_returnProductButtonActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.INCOMMING_PRODUCT)) {
            return;
        }

        mainForm.incomingProduct();
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void showCassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCassButtonActionPerformed

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.SHOW_CASS)) {
            return;
        }

        mainForm.showPanel("MoneyOperationMainPanel");
    }//GEN-LAST:event_showCassButtonActionPerformed

    private void removeProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProductButtonActionPerformed

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.OUTCOMMING_PRODUCT)) {
            return;
        }

        mainForm.outcommingProduct();
    }//GEN-LAST:event_removeProductButtonActionPerformed

    private void addMoneyToBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoneyToBalanceButtonActionPerformed

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.ADD_MONEY_TO_CUSTOMER_BALANCE)) {
            return;
        }

        mainForm.addMoneyToCustomerBalance();
    }//GEN-LAST:event_addMoneyToBalanceButtonActionPerformed

    private void removeMoneyFromCassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMoneyFromCassButtonActionPerformed

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.REMOV_MONEY)) {
            return;
        }

        mainForm.removeMoneyFromCass();
    }//GEN-LAST:event_removeMoneyFromCassButtonActionPerformed

    private void removeMoneyFromBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMoneyFromBalanceButtonActionPerformed

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.REMOV_MONEY_FROM_CUSTOMER_BALANCE)) {
            return;
        }

        mainForm.removMoneyFromCustomerBalance();
    }//GEN-LAST:event_removeMoneyFromBalanceButtonActionPerformed

    @Override
    public void updateContent() {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public Icon getCaptionIcon() {
        return new javax.swing.ImageIcon(getClass().getResource("/tradeterminal/icons/TT_icons/32X32/navi.png"));
    }

    @Override
    public String getCaptionText() {
        return "Навигация";
    }

    @Override
    public List<JMenuItem> getMenuItemList() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMoneyToBalanceButton;
    private javax.swing.JButton addMoneyToCassButton;
    private javax.swing.JButton addProductButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton removeMoneyFromBalanceButton;
    private javax.swing.JButton removeMoneyFromCassButton;
    private javax.swing.JButton removeProductButton;
    private javax.swing.JButton returnProductButton;
    private javax.swing.JButton selProductButton;
    private javax.swing.JButton showCassButton;
    // End of variables declaration//GEN-END:variables
}
