/*
 * ProductDPanelV2.java
 *
 * Created on 22 Май 2008 г., 0:19
 */
package tt.reports.product_movong_v2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import minersinstrument.db.ADBProc;
import minersinstrument.db.PADBUtils;
import minersinstrument.db.PADBUtils.PADBResult;
import minersinstrument.ui.IADialogPanel;
import org.postgresql.ds.PGPoolingDataSource;

/**
 *
 * @author  pkopychenko
 */
public class TTRProductDPanelV2 extends javax.swing.JPanel implements IADialogPanel {


    private class UserItem {
        private int id;
        private String userName;

        public UserItem(int id, String userName) {
            this.id = id;
            this.userName = userName;
        }

        public int getId() {
            return id;
        }

        public String getUserName() {
            return userName;
        }

        @Override
        public String toString() {
            return this.userName;
        }


    }

    /** Creates new form ProductDPanelV2 */
    public TTRProductDPanelV2(PGPoolingDataSource source) {

        initComponents();
        beginDatePicker.setDate(new Date());
        endDatePicker.setDate(new Date());

        List<UserItem> users = new ArrayList<UserItem>();

        PADBResult result = null;
        try {

            ADBProc proc = new ADBProc("users_select_for_loginer");
            result = PADBUtils.getResultSet(source, proc);
            ResultSet rs = result.getRs();
            while (rs.next()) {
                users.add(new UserItem(rs.getInt("id"), rs.getString("name")));
            }

        } catch (SQLException ex) {
            Logger.getLogger(TTRProductDPanelV2.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            result.close();
        }
        DefaultComboBoxModel bcbm = new DefaultComboBoxModel(users.toArray());

        usersComboBox.setModel(bcbm);
    }

    public Date getBeginDate() {
        return beginDatePicker.getDate();
    }

    public void setBeginDate(Date d) {
        this.beginDatePicker.setDate(d);
    }

    public Date getEndDate() {
        return endDatePicker.getDate();
    }

    public void setEndDate(Date d) {
        this.endDatePicker.setDate(d);
    }

    public boolean isPMN() {
        return checkBoxPMN.isSelected();
    }

    public boolean isPPL() {
        return checkBoxPPL.isSelected();
    }

    public boolean isPRT() {
        return checkBoxPRT.isSelected();
    }

    public boolean isPSL() {
        return checkBoxPSL.isSelected();
    }

    public boolean isUserSelected() {
        return usersCheckBox.isSelected();
    }
    
    public int getSelectedUserId(){
        return ((UserItem)usersComboBox.getSelectedItem()).getId();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        beginDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        endDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jPanel1 = new javax.swing.JPanel();
        checkBoxPPL = new javax.swing.JCheckBox();
        checkBoxPMN = new javax.swing.JCheckBox();
        checkBoxPSL = new javax.swing.JCheckBox();
        checkBoxPRT = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        usersCheckBox = new javax.swing.JCheckBox();
        usersComboBox = new javax.swing.JComboBox();

        setName("Form"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("За промежуток:"));
        jPanel2.setName("jPanel2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(TTRProductDPanelV2.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        beginDatePicker.setName("beginDatePicker"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        endDatePicker.setName("endDatePicker"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(endDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beginDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(beginDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Отобразить:"));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        checkBoxPPL.setText(resourceMap.getString("checkBoxPPL.text")); // NOI18N
        checkBoxPPL.setName("checkBoxPPL"); // NOI18N
        jPanel1.add(checkBoxPPL);

        checkBoxPMN.setText(resourceMap.getString("checkBoxPMN.text")); // NOI18N
        checkBoxPMN.setName("checkBoxPMN"); // NOI18N
        jPanel1.add(checkBoxPMN);

        checkBoxPSL.setText(resourceMap.getString("checkBoxPSL.text")); // NOI18N
        checkBoxPSL.setName("checkBoxPSL"); // NOI18N
        jPanel1.add(checkBoxPSL);

        checkBoxPRT.setText(resourceMap.getString("checkBoxPRT.text")); // NOI18N
        checkBoxPRT.setName("checkBoxPRT"); // NOI18N
        jPanel1.add(checkBoxPRT);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel3.border.title"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        usersCheckBox.setText(resourceMap.getString("usersCheckBox.text")); // NOI18N
        usersCheckBox.setName("usersCheckBox"); // NOI18N
        usersCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersCheckBoxActionPerformed(evt);
            }
        });

        usersComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        usersComboBox.setEnabled(false);
        usersComboBox.setName("usersComboBox"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersCheckBox)
                    .addComponent(usersComboBox, 0, 248, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(usersCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usersCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersCheckBoxActionPerformed
        usersComboBox.setEnabled(usersCheckBox.isSelected());
    }//GEN-LAST:event_usersCheckBoxActionPerformed

    @Override
    public boolean checkPanel() {

        if (!checkBoxPMN.isSelected()
                & !checkBoxPPL.isSelected()
                & !checkBoxPRT.isSelected()
                & !checkBoxPSL.isSelected()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Выберите хотябы один тип операции для отображения",
                    "Внимание...",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    @Override
    public void openPanel() {
        beginDatePicker.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker beginDatePicker;
    private javax.swing.JCheckBox checkBoxPMN;
    private javax.swing.JCheckBox checkBoxPPL;
    private javax.swing.JCheckBox checkBoxPRT;
    private javax.swing.JCheckBox checkBoxPSL;
    private org.jdesktop.swingx.JXDatePicker endDatePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox usersCheckBox;
    private javax.swing.JComboBox usersComboBox;
    // End of variables declaration//GEN-END:variables
}
