/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MoveProductDialog.java
 *
 * Created on 08.02.2011, 14:41:46
 */

package tradeterminal.products;

import minersinstrument.ui.IADialogPanel;

/**
 *
 * @author Admin
 */
public class MoveProductDialog extends javax.swing.JPanel implements IADialogPanel{

    /** Creates new form MoveProductDialog */
    public MoveProductDialog() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toGroupName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scod = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getResourceMap(MoveProductDialog.class);
        toGroupName.setFont(resourceMap.getFont("toGroupName.font")); // NOI18N
        toGroupName.setText(resourceMap.getString("toGroupName.text")); // NOI18N
        toGroupName.setName("toGroupName"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        productName.setFont(resourceMap.getFont("productName.font")); // NOI18N
        productName.setText(resourceMap.getString("productName.text")); // NOI18N
        productName.setName("productName"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        scod.setFont(resourceMap.getFont("scod.font")); // NOI18N
        scod.setText(resourceMap.getString("scod.text")); // NOI18N
        scod.setName("scod"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toGroupName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scod)))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(toGroupName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(productName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(scod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Наименование продукта
     * @param productName
     */
    public void setProductName(String productName) {
        this.productName.setText(productName);
    }

    /**
     * Штрихкод продукта
     * @param scod
     */
    public void setScod(String scod) {
        this.scod.setText(scod);
    }

    /**
     * Наименование группы, куда надо переместить продут
     * @param toGroupName
     */
    public void setToGroupName(String toGroupName) {
        this.toGroupName.setText(toGroupName);
    }

    @Override
    public boolean checkPanel() {
        return true;
    }

    @Override
    public void openPanel() {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel scod;
    private javax.swing.JLabel toGroupName;
    // End of variables declaration//GEN-END:variables
}
