/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetOrderIDDPanel.java
 *
 * Created on 07.08.2012, 21:39:12
 */
package pk.reports.ttrnakl;

import minersinstrument.ui.IADialogPanel;

/**
 *
 * @author dev_tt
 */
public class SetOrderIDDPanel extends javax.swing.JPanel implements IADialogPanel {

    /** Creates new form SetOrderIDDPanel */
    public SetOrderIDDPanel() {
        initComponents();
    }

    @Override
    public boolean checkPanel() {
        return true;
    }

    @Override
    public void openPanel() {
        orderFormattedTextField.requestFocus();
    }

    public Number getOrderFormattedTextField() {
        return (Number) orderFormattedTextField.getValue();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();

        orderFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        orderFormattedTextField.setName("orderFormattedTextField"); // NOI18N

        jLabel6.setText("Ордер №");
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(orderFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField orderFormattedTextField;
    // End of variables declaration//GEN-END:variables
}
