/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddEditDBDPanel.java
 *
 * Created on 10.02.2009, 20:23:54
 */
package installdb.dialogs;

import java.util.Arrays;
import javax.swing.JOptionPane;
import minersinstrument.ui.IADialogPanel;


/**
 *
 * @author pacman
 */
public class AddEditDBDPanel extends javax.swing.JPanel implements IADialogPanel {

    /** Creates new form AddEditDBDPanel */
    public AddEditDBDPanel() {
        initComponents();
    }

    public void setCaption(String s) {
        captionTextField.setText(s);
    }

    public String getCaption() {
        return captionTextField.getText();
    }

    public void setBase(String s){
        baseTextField.setText(s);
    }

    public String getBase(){
        return baseTextField.getText();
    }

    public void setUser(String s){
        userTextField.setText(s);
    }

    public String getUser(){
        return userTextField.getText();
    }

    public char[] getPassword() {
        return passwordField2.getPassword();
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        captionTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        baseTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        passwordField2 = new javax.swing.JPasswordField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(installdb.InstallDBApp.class).getContext().getResourceMap(AddEditDBDPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        captionTextField.setText(resourceMap.getString("captionTextField.text")); // NOI18N
        captionTextField.setName("captionTextField"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        baseTextField.setText(resourceMap.getString("baseTextField.text")); // NOI18N
        baseTextField.setName("baseTextField"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        userTextField.setText(resourceMap.getString("userTextField.text")); // NOI18N
        userTextField.setName("userTextField"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        passwordField1.setText(resourceMap.getString("passwordField1.text")); // NOI18N
        passwordField1.setName("passwordField1"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        passwordField2.setText(resourceMap.getString("passwordField2.text")); // NOI18N
        passwordField2.setName("passwordField2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(passwordField1)
                    .addComponent(baseTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(captionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(captionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkPanel() {

        if(captionTextField.getText().length() == 0){
            JOptionPane.showMessageDialog(
                    this,
                    "Вы не ввели название.",
                    "Внимание...",
                    JOptionPane.WARNING_MESSAGE);
            captionTextField.requestFocus();
            return false;
        } else if(baseTextField.getText().length() == 0){
            JOptionPane.showMessageDialog(
                    this,
                    "Вы не ввели название базы данных.",
                    "Внимание...",
                    JOptionPane.WARNING_MESSAGE);
            baseTextField.requestFocus();
            return false;
        } else if(userTextField.getText().length() == 0){
            JOptionPane.showMessageDialog(
                    this,
                    "Вы не ввели имя пользователя базы данных.",
                    "Внимание...",
                    JOptionPane.WARNING_MESSAGE);
            userTextField.requestFocus();
            return false;
        } else if(!Arrays.equals(passwordField1.getPassword(),
                (passwordField2.getPassword()))){
            JOptionPane.showMessageDialog(
                    this,
                    "Пароли не совпадают.",
                    "Внимание...",
                    JOptionPane.WARNING_MESSAGE);
            passwordField1.requestFocus();
            return false;
        }


        return true;
    }

    public void openPanel() {
        captionTextField.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baseTextField;
    private javax.swing.JTextField captionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
