/*
 * RBDocTypesMainPanel.java
 *
 * Created on 13 Август 2008 г., 21:56
 */
package tradeterminal.references_books.doc_types;

import java.awt.Dimension;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JMenuItem;
import org.jdesktop.application.Action;
import tradeterminal.IPage;
import tradeterminal.Setup;
import tradeterminal.conf.AppAccessSettings;

/**
 *
 * @author  pacman
 */
public final class RBDocTypesMainPanel extends javax.swing.JPanel implements IPage {

    private RBDocTypesAdapter adapter = new RBDocTypesAdapter(Setup.getSource());

    /** Creates new form RBDocTypesMainPanel */
    public RBDocTypesMainPanel() {
        initComponents();

        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(32, 32));
        jScrollPane1.getHorizontalScrollBar().setPreferredSize(new Dimension(32, 32));

        aDBJXTable.setAdapter(adapter);

        aDBJXTable.getColumnModel().removeColumn(aDBJXTable.getColumnModel().getColumn(0));

        aDBJXTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        aDBJXTable.getColumnModel().getColumn(0).setHeaderValue("Наименование");
        aDBJXTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        aDBJXTable.getColumnModel().getColumn(1).setHeaderValue("Описание");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        aDBJXTable = new minersinstrument.ui.ADBJXTable();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getActionMap(RBDocTypesMainPanel.class, this);
        addButton.setAction(actionMap.get("addRow")); // NOI18N
        addButton.setName("addButton"); // NOI18N
        jPanel1.add(addButton);

        editButton.setAction(actionMap.get("editRow")); // NOI18N
        editButton.setName("editButton"); // NOI18N
        jPanel1.add(editButton);

        delButton.setAction(actionMap.get("delRow")); // NOI18N
        delButton.setName("delButton"); // NOI18N
        jPanel1.add(delButton);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        aDBJXTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        aDBJXTable.setName("aDBJXTable"); // NOI18N
        jScrollPane1.setViewportView(aDBJXTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void addRow() {

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.RB_EDIT)) {
            return;
        }

        aDBJXTable.addRow();
    }

    @Action
    public void editRow() {

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.RB_EDIT)) {
            return;
        }

        aDBJXTable.editRow();
    }

    @Action
    public void delRow() {

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.RB_EDIT)) {
            return;
        }

        aDBJXTable.delRow();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private minersinstrument.ui.ADBJXTable aDBJXTable;
    private javax.swing.JButton addButton;
    private javax.swing.JButton delButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateContent() {
        aDBJXTable.updateRows();
    }

    @Override
    public Icon getCaptionIcon() {
        return new javax.swing.ImageIcon(getClass().getResource("/tradeterminal/icons/TT_icons/32X32/tipydok.png"));
    }

    @Override
    public String getCaptionText() {
        return "Справочник типов документов";
    }

    @Override
    public List<JMenuItem> getMenuItemList() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
