/*
 * AddOrRemoveMoneyToCustomerBalance.java
 *
 * Created on 15 Сентябрь 2008 г., 20:42
 */
package tradeterminal.operations.money.customerbalahce.p0;

import java.awt.Dimension;
import java.sql.Types;
import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import minersinstrument.db.ADBProc;
import minersinstrument.db.ADBProcParametr;
import minersinstrument.db.PADBUtils;
import minersinstrument.ui.ADialogFocusLisner;
import minersinstrument.ui.AUniversalDialog;
import minersinstrument.ui.IADialogPanel;
import org.jdesktop.application.Action;
import minersinstrument.ui.ADialog;
import minersinstrument.ui.AUniversalCloseDialog;
import tradeterminal.Setup;
import tradeterminal.conf.User;
import tradeterminal.references_books.customers.p0.CustomerBalanseHistoryDPanel;
import tradeterminal.references_books.customers.p0.FindCustomerDPAnel;

/**
 *
 * @author  pacman
 */
public abstract class MoneyToCustomerBalanceBase extends javax.swing.JPanel implements IADialogPanel {

    private int costumerId = -1;
    private double customerBalance = 0;
    private DecimalFormat df = new DecimalFormat();

    /** Creates new form AddOrRemoveMoneyToCustomerBalance */
    public MoneyToCustomerBalanceBase() {
        initComponents();

        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(32, 32));
        jScrollPane1.getHorizontalScrollBar().setPreferredSize(new Dimension(32, 32));

        jScrollPane2.getVerticalScrollBar().setPreferredSize(new Dimension(32, 32));
        jScrollPane2.getHorizontalScrollBar().setPreferredSize(new Dimension(32, 32));


        moneySpinner.setModel(new SpinnerNumberModel(
                Double.valueOf(0.0f),
                Double.valueOf(0.0f),
                Double.valueOf(1000000000),
                Double.valueOf(0.01f)));

        ADialogFocusLisner adf = new ADialogFocusLisner();

        ((JSpinner.DefaultEditor) moneySpinner.getEditor()).getTextField().addFocusListener(adf);
        ((JSpinner.DefaultEditor) moneySpinner.getEditor()).getTextField().addKeyListener(new java.awt.event.KeyAdapter() {

            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                moneySpinnerStateChanged(null);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        moneySpinner = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerInfoTextArea = new javax.swing.JTextArea();
        findCustomerButton = new javax.swing.JButton();
        showCustomerBalanceButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        curentBalanceLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newBalanceLabel = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getResourceMap(MoneyToCustomerBalanceBase.class);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(resourceMap.getFont("descriptionTextArea.font")); // NOI18N
        descriptionTextArea.setRows(5);
        descriptionTextArea.setName("descriptionTextArea"); // NOI18N
        jScrollPane1.setViewportView(descriptionTextArea);

        moneySpinner.setFont(resourceMap.getFont("moneySpinner.font")); // NOI18N
        moneySpinner.setName("moneySpinner"); // NOI18N
        moneySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                moneySpinnerStateChanged(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Клиент:"));
        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        customerInfoTextArea.setColumns(30);
        customerInfoTextArea.setEditable(false);
        customerInfoTextArea.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        customerInfoTextArea.setLineWrap(true);
        customerInfoTextArea.setRows(5);
        customerInfoTextArea.setName("customerInfoTextArea"); // NOI18N
        jScrollPane2.setViewportView(customerInfoTextArea);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getActionMap(MoneyToCustomerBalanceBase.class, this);
        findCustomerButton.setAction(actionMap.get("findCustomer")); // NOI18N
        findCustomerButton.setName("findCustomerButton"); // NOI18N

        showCustomerBalanceButton.setAction(actionMap.get("showCustomerBalanceList")); // NOI18N
        showCustomerBalanceButton.setName("showCustomerBalanceButton"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        curentBalanceLabel.setFont(resourceMap.getFont("curentBalanceLabel.font")); // NOI18N
        curentBalanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        curentBalanceLabel.setText(resourceMap.getString("curentBalanceLabel.text")); // NOI18N
        curentBalanceLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        curentBalanceLabel.setName("curentBalanceLabel"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        newBalanceLabel.setFont(resourceMap.getFont("newBalanceLabel.font")); // NOI18N
        newBalanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newBalanceLabel.setText(resourceMap.getString("newBalanceLabel.text")); // NOI18N
        newBalanceLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        newBalanceLabel.setName("newBalanceLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(findCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(showCustomerBalanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(newBalanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(curentBalanceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moneySpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(findCustomerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showCustomerBalanceButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(curentBalanceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newBalanceLabel)
                            .addComponent(jLabel7))
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(132, 132, 132)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void openPanel() {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Action
    public void findCustomer() {
        FindCustomerDPAnel p = new FindCustomerDPAnel();
        AUniversalDialog d = new AUniversalDialog(p, null, true);
        d.setTitleIcon(new javax.swing.ImageIcon(getClass().getResource("/tradeterminal/icons/TT_icons/32X32/polzovatel.png")));
        d.setTitle("Поиск клиента");
        d.setTitleText("Поиск клиента");

        d.setVisible(true);
        d.dispose();

        findBase(d, p);
    }

    /**
     * Базовая обработка поиска
     * @param d
     * @param p
     */
    protected void findBase( ADialog d, FindCustomerDPAnel p){
         if (d.getReturnStatus() == ADialog.RET_OK) {
            costumerId = p.getSelectedId();
            customerInfoTextArea.setText(p.getCustomerInfo());
            customerInfoTextArea.select(0, 1);

            customerBalance = p.getBalance();

        } else {
            customerInfoTextArea.setText("");
            costumerId = -1;
            customerBalance = 0;
        }

        curentBalanceLabel.setText("" + customerBalance);

        moneySpinnerStateChanged(null);
    }


    @Action
    public void showCustomerBalanceList() {

        if (costumerId == -1) {
            return;
        }

        CustomerBalanseHistoryDPanel p =
                new CustomerBalanseHistoryDPanel(costumerId);
        AUniversalCloseDialog d = new AUniversalCloseDialog(p, null, true);
        d.setTitleIcon(new javax.swing.ImageIcon(getClass().getResource("/tradeterminal/icons/TT_icons/32X32/istoriya.png")));
        d.setTitle("История");
        d.setTitleText("История");

        d.setResizable(true);

        d.setVisible(true);
        d.dispose();

    }

    @Override
    public boolean checkPanel() {

        if (costumerId == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Выберите клиента.",
                    "Информация",
                    JOptionPane.INFORMATION_MESSAGE);

            return false;
        }



        try {

            moneySpinner.commitEdit();
        } catch (ParseException ex) {
            ((JSpinner.DefaultEditor) moneySpinner.getEditor()).getTextField().requestFocus();
            return false;
        }


        if (((Number) moneySpinner.getValue()).doubleValue() == 0) {
            ((JSpinner.DefaultEditor) moneySpinner.getEditor()).getTextField().requestFocus();

            JOptionPane.showMessageDialog(
                    this,
                    "Введите сумму.",
                    "Информация",
                    JOptionPane.INFORMATION_MESSAGE);


            return false;
        }


        double summ = getSumm((Double) moneySpinner.getValue());

        System.out.println("add to customer balance " + summ);

        // Выполнить SQL функцию
        ADBProc proc = new ADBProc("customer_add_money_to_balance");
        proc.addInParametr(new ADBProcParametr(Types.INTEGER, new Integer(costumerId)));
        proc.addInParametr(new ADBProcParametr(Types.NUMERIC, new Double(summ)));
        proc.addInParametr(new ADBProcParametr(Types.VARCHAR, descriptionTextArea.getText()));
        proc.addInParametr(new ADBProcParametr(Types.INTEGER, new Integer(User.id)));

        PADBUtils.executeVoidProcedure(Setup.getSource(), proc);


        return true;
    }

    protected abstract double getSumm(double d);

    private void moneySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_moneySpinnerStateChanged

        double newBalance = 0;

        try {
            //moneySpinner.commitEdit();


            newBalance = getSumm(df.parse(((JSpinner.DefaultEditor) moneySpinner.getEditor()).getTextField().getText()).doubleValue());

            newBalance += customerBalance;

            System.out.println(moneySpinner.getValue().getClass().toString());



        } catch (ParseException ex) {
            newBalance = 0;
        }

        newBalanceLabel.setText("" + df.format(newBalance));

    }//GEN-LAST:event_moneySpinnerStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel curentBalanceLabel;
    protected javax.swing.JTextArea customerInfoTextArea;
    protected javax.swing.JTextArea descriptionTextArea;
    protected javax.swing.JButton findCustomerButton;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel5;
    protected javax.swing.JLabel jLabel7;
    protected javax.swing.JPanel jPanel8;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JSpinner moneySpinner;
    protected javax.swing.JLabel newBalanceLabel;
    protected javax.swing.JButton showCustomerBalanceButton;
    // End of variables declaration//GEN-END:variables
}
