/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OptionsPanel.java
 *
 * Created on 24.02.2011, 19:05:16
 */
package tradeterminal.conf.options_dialogs;

import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.DefaultComboBoxModel;
import minersinstrument.ui.IADialogPanel;
import tradeterminal.conf.AppConstants;
import minersinstrument.savesettings.csettings.CSettingsTools;
import tradeterminal.conf.db_params.DBParams;

/**
 *
 * @author tt
 */
public class OptionsPanel extends javax.swing.JPanel implements IADialogPanel {
    
    class CheckPrinterComboBoxModel extends DefaultComboBoxModel{

       
    }
    
    
    

    /** Creates new form OptionsPanel */
    public OptionsPanel() {
        initComponents();

        nameTextField.setText(CSettingsTools.getStringValue(AppConstants.APP_CLIENT_NAME_KEY));
        phonesTextField.setText(CSettingsTools.getStringValue(AppConstants.APP_CLIENT_PHONES_KEY));
        addressTextPane1.setText(CSettingsTools.getStringValue(AppConstants.APP_CLIENT_ADDRESS_KEY));
        descriptionTextPane.setText(CSettingsTools.getStringValue(AppConstants.APP_CLIENT_DESCRIPTION_KEY));

        dbNameTextField.setText(DBParams.getStringValue(DBParams.DB_NAME));
        dbDescriptionTextPane.setText(DBParams.getStringValue(DBParams.DB_DESCRIPTION));


        enableEVCheckBox.setSelected(DBParams.getBooleanValue(DBParams.EV));
        evMassCharCountSpinner.setValue(DBParams.getNumberValue(DBParams.EV_MASS_CHAR_COUNT));
        evKfMassCountSpinner.setValue(DBParams.getNumberValue(DBParams.EV_KF_MASS).doubleValue());
        evScodeCharCountSpinner.setValue(DBParams.getNumberValue(DBParams.EV_SCODE_CHAR_COUNT));
        evPrefixTextField.setText(DBParams.getStringValue(DBParams.EV_SCODE_PREFIX));

        enableEVCheckBoxActionPerformed(null);


        enableShowQuantitySelingDialogCheckBox.setSelected(CSettingsTools.getBooleanValue(AppConstants.ENABLE_SHOW_QUANTITY_SELING_DIALOG));
        
                
        // Принтер чеков ----------------------------------------------------------------------
        
        
        /* Create an array of PrintServices */        
        DefaultComboBoxModel<String> checkPrinterComboBoxModel = new DefaultComboBoxModel<>();
        PrintService[] services = PrintServiceLookup.lookupPrintServices(null, null);
        for(PrintService ps: services){
            checkPrinterComboBoxModel.addElement(ps.getName());
        }
        
        checkPrinterComboBox.setModel(checkPrinterComboBoxModel);
        checkPrinterComboBox.setSelectedItem(CSettingsTools.getStringValue(AppConstants.CHECK_PRINTER));
        
        checkHeadTextField.setText(DBParams.getStringValue(DBParams.CHECK_HEAD));
        checkCaptionTextField.setText(DBParams.getStringValue(DBParams.CHECK_CAPTION));
        
        paginationCheckBox.setSelected(CSettingsTools.getBooleanValue(AppConstants.CHECK_PAGINATION));
        pageHeightSpinner.setValue(CSettingsTools.getIntValue(AppConstants.CHECK_PAGE_HEIGHT));
        // rendering
        pageHeightSpinner.setEnabled(paginationCheckBox.isSelected());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        phonesTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextPane = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        dbNameTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        dbDescriptionTextPane = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        enableShowQuantitySelingDialogCheckBox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        evPrefixTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        enableEVCheckBox = new javax.swing.JCheckBox();
        evScodeCharCountSpinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        evMassCharCountSpinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        evKfMassCountSpinner = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        checkPrinterComboBox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        checkHeadTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        checkCaptionTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        paginationCheckBox = new javax.swing.JCheckBox();
        pageHeightSpinner = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(OptionsPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        nameTextField.setText(resourceMap.getString("nameTextField.text")); // NOI18N
        nameTextField.setName("nameTextField"); // NOI18N

        phonesTextField.setText(resourceMap.getString("phonesTextField.text")); // NOI18N
        phonesTextField.setName("phonesTextField"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        addressTextPane1.setName("addressTextPane1"); // NOI18N
        jScrollPane1.setViewportView(addressTextPane1);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        descriptionTextPane.setName("descriptionTextPane"); // NOI18N
        jScrollPane2.setViewportView(descriptionTextPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(phonesTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(phonesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        dbNameTextField.setText(resourceMap.getString("dbNameTextField.text")); // NOI18N
        dbNameTextField.setName("dbNameTextField"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        dbDescriptionTextPane.setName("dbDescriptionTextPane"); // NOI18N
        jScrollPane3.setViewportView(dbDescriptionTextPane);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(dbNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        jLabel11.setBackground(resourceMap.getColor("jLabel11.background")); // NOI18N
        jLabel11.setForeground(resourceMap.getColor("jLabel11.foreground")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setToolTipText(resourceMap.getString("jLabel11.toolTipText")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        enableShowQuantitySelingDialogCheckBox.setText(resourceMap.getString("enableShowQuantitySelingDialogCheckBox.text")); // NOI18N
        enableShowQuantitySelingDialogCheckBox.setName("enableShowQuantitySelingDialogCheckBox"); // NOI18N
        enableShowQuantitySelingDialogCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableShowQuantitySelingDialogCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enableShowQuantitySelingDialogCheckBox)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enableShowQuantitySelingDialogCheckBox)
                .addGap(238, 238, 238))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        evPrefixTextField.setText(resourceMap.getString("evPrefixTextField.text")); // NOI18N
        evPrefixTextField.setName("evPrefixTextField"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        enableEVCheckBox.setText(resourceMap.getString("enableEVCheckBox.text")); // NOI18N
        enableEVCheckBox.setName("enableEVCheckBox"); // NOI18N
        enableEVCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableEVCheckBoxActionPerformed(evt);
            }
        });

        evScodeCharCountSpinner.setName("evScodeCharCountSpinner"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        evMassCharCountSpinner.setName("evMassCharCountSpinner"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setBackground(resourceMap.getColor("jLabel10.background")); // NOI18N
        jLabel10.setForeground(resourceMap.getColor("jLabel10.foreground")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setToolTipText(resourceMap.getString("jLabel10.toolTipText")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        evKfMassCountSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        evKfMassCountSpinner.setName("evKfMassCountSpinner"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .addComponent(enableEVCheckBox)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(evPrefixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(evKfMassCountSpinner)
                            .addComponent(evMassCharCountSpinner)
                            .addComponent(evScodeCharCountSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(enableEVCheckBox)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(evPrefixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(evScodeCharCountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(evMassCharCountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(evKfMassCountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        checkPrinterComboBox.setName("checkPrinterComboBox"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        checkHeadTextField.setText(resourceMap.getString("checkHeadTextField.text")); // NOI18N
        checkHeadTextField.setName("checkHeadTextField"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        checkCaptionTextField.setText(resourceMap.getString("checkCaptionTextField.text")); // NOI18N
        checkCaptionTextField.setName("checkCaptionTextField"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        paginationCheckBox.setText(resourceMap.getString("paginationCheckBox.text")); // NOI18N
        paginationCheckBox.setName("paginationCheckBox"); // NOI18N
        paginationCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginationCheckBoxActionPerformed(evt);
            }
        });

        pageHeightSpinner.setName("pageHeightSpinner"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkCaptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(checkHeadTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(checkPrinterComboBox, 0, 396, Short.MAX_VALUE)
                    .addComponent(paginationCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(pageHeightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkPrinterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkHeadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkCaptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paginationCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageHeightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel5.TabConstraints.tabTitle"), jPanel5); // NOI18N

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void enableEVCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableEVCheckBoxActionPerformed
        evMassCharCountSpinner.setEnabled(enableEVCheckBox.isSelected());
        evScodeCharCountSpinner.setEnabled(enableEVCheckBox.isSelected());
        evPrefixTextField.setEnabled(enableEVCheckBox.isSelected());
        evKfMassCountSpinner.setEnabled(enableEVCheckBox.isSelected());
    }//GEN-LAST:event_enableEVCheckBoxActionPerformed

    private void enableShowQuantitySelingDialogCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableShowQuantitySelingDialogCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enableShowQuantitySelingDialogCheckBoxActionPerformed

    private void paginationCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginationCheckBoxActionPerformed
        pageHeightSpinner.setEnabled(paginationCheckBox.isSelected());
    }//GEN-LAST:event_paginationCheckBoxActionPerformed

    @Override
    public boolean checkPanel() {

        CSettingsTools.setVal(AppConstants.APP_CLIENT_NAME_KEY, nameTextField.getText());
        CSettingsTools.setVal(AppConstants.APP_CLIENT_PHONES_KEY, phonesTextField.getText());
        CSettingsTools.setVal(AppConstants.APP_CLIENT_ADDRESS_KEY, addressTextPane1.getText());
        CSettingsTools.setVal(AppConstants.APP_CLIENT_DESCRIPTION_KEY, descriptionTextPane.getText());
        
        CSettingsTools.setVal(AppConstants.ENABLE_SHOW_QUANTITY_SELING_DIALOG, enableShowQuantitySelingDialogCheckBox.isSelected());
        CSettingsTools.setVal(AppConstants.CHECK_PRINTER, checkPrinterComboBox.getSelectedItem());
        
        CSettingsTools.setVal(AppConstants.CHECK_PAGINATION, paginationCheckBox.isSelected());
        CSettingsTools.setVal(AppConstants.CHECK_PAGE_HEIGHT, pageHeightSpinner.getValue());
        

        CSettingsTools.saveCs();

        DBParams.addOrUpdateDBParametr(
                DBParams.DB_NAME, dbNameTextField.getText(), null, null, null);

        DBParams.addOrUpdateDBParametr(
                DBParams.DB_DESCRIPTION, dbDescriptionTextPane.getText(), null, null, null);

        DBParams.addOrUpdateDBParametr(DBParams.EV, null, null, null, enableEVCheckBox.isSelected());
        DBParams.addOrUpdateDBParametr(DBParams.EV_MASS_CHAR_COUNT, null, (Number) evMassCharCountSpinner.getValue(), null, null);
        DBParams.addOrUpdateDBParametr(DBParams.EV_KF_MASS, null, (Number) evKfMassCountSpinner.getValue(), null, null);
        DBParams.addOrUpdateDBParametr(DBParams.EV_SCODE_CHAR_COUNT, null, (Number) evScodeCharCountSpinner.getValue(), null, null);
        DBParams.addOrUpdateDBParametr(DBParams.EV_SCODE_PREFIX, evPrefixTextField.getText(), null, null, null);
        
        DBParams.addOrUpdateDBParametr(DBParams.CHECK_HEAD, checkHeadTextField.getText(), null, null, null);
        DBParams.addOrUpdateDBParametr(DBParams.CHECK_CAPTION, checkCaptionTextField.getText(), null, null, null);

        return true;
    }

    @Override
    public void openPanel() {
        nameTextField.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane addressTextPane1;
    private javax.swing.JTextField checkCaptionTextField;
    private javax.swing.JTextField checkHeadTextField;
    private javax.swing.JComboBox checkPrinterComboBox;
    private javax.swing.JTextPane dbDescriptionTextPane;
    private javax.swing.JTextField dbNameTextField;
    private javax.swing.JTextPane descriptionTextPane;
    private javax.swing.JCheckBox enableEVCheckBox;
    private javax.swing.JCheckBox enableShowQuantitySelingDialogCheckBox;
    private javax.swing.JSpinner evKfMassCountSpinner;
    private javax.swing.JSpinner evMassCharCountSpinner;
    private javax.swing.JTextField evPrefixTextField;
    private javax.swing.JSpinner evScodeCharCountSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JSpinner pageHeightSpinner;
    private javax.swing.JCheckBox paginationCheckBox;
    private javax.swing.JTextField phonesTextField;
    // End of variables declaration//GEN-END:variables
}
