/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TTRProductsQuantitysDPanel.java
 *
 * Created on 25.03.2011, 0:00:37
 */
package tt.reports.products_quantitys;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import minersinstrument.ui.ADialog;
import minersinstrument.ui.AUniversalDialog;
import minersinstrument.ui.IADialogPanel;
import org.jdesktop.application.Action;

/**
 *
 * @author tt
 */
public class TTRProductsQuantitysDPanel extends javax.swing.JPanel implements IADialogPanel {

    /** Creates new form TTRProductsQuantitysDPanel */
    public TTRProductsQuantitysDPanel() {
        initComponents();
    }

    public double getbBetween() {
        return (Double) bBetweenSpinner.getValue();
    }

    public boolean getIsBetween() {
        return betweenRadioButton.isSelected();
    }

    public double geteBetween() {
        return (Double) eBetweenSpinner.getValue();
    }

    public boolean getIsLess() {
        return lessRadioButton.isSelected();
    }

    public double getLess() {
        return (Double) lessSpinner.getValue();
    }

    public boolean getIsMore() {
        return moreRadioButton.isSelected();
    }

    public double getMore() {
        return (Double) moreSpinner.getValue();
    }

    public boolean getIsWell() {
        return wellRadioButton.isSelected();
    }

    public double getWell() {
        return (Double) wellSpinner.getValue();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qvariantButtonGroup = new javax.swing.ButtonGroup();
        betweenRadioButton = new javax.swing.JRadioButton();
        moreRadioButton = new javax.swing.JRadioButton();
        lessRadioButton = new javax.swing.JRadioButton();
        wellRadioButton = new javax.swing.JRadioButton();
        bBetweenSpinner = new javax.swing.JSpinner();
        eBetweenSpinner = new javax.swing.JSpinner();
        moreSpinner = new javax.swing.JSpinner();
        lessSpinner = new javax.swing.JSpinner();
        wellSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(TTRProductsQuantitysDPanel.class, this);
        betweenRadioButton.setAction(actionMap.get("selectVariant")); // NOI18N
        qvariantButtonGroup.add(betweenRadioButton);
        betweenRadioButton.setSelected(true);
        betweenRadioButton.setText("В указанном диапазоне");
        betweenRadioButton.setName("betweenRadioButton"); // NOI18N

        moreRadioButton.setAction(actionMap.get("selectVariant")); // NOI18N
        qvariantButtonGroup.add(moreRadioButton);
        moreRadioButton.setText("Больше чем");
        moreRadioButton.setName("moreRadioButton"); // NOI18N

        lessRadioButton.setAction(actionMap.get("selectVariant")); // NOI18N
        qvariantButtonGroup.add(lessRadioButton);
        lessRadioButton.setText("Меньше чем");
        lessRadioButton.setName("lessRadioButton"); // NOI18N

        wellRadioButton.setAction(actionMap.get("selectVariant")); // NOI18N
        qvariantButtonGroup.add(wellRadioButton);
        wellRadioButton.setText("Равно");
        wellRadioButton.setName("wellRadioButton"); // NOI18N

        bBetweenSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        bBetweenSpinner.setName("bBetweenSpinner"); // NOI18N

        eBetweenSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        eBetweenSpinner.setName("eBetweenSpinner"); // NOI18N

        moreSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        moreSpinner.setEnabled(false);
        moreSpinner.setName("moreSpinner"); // NOI18N

        lessSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        lessSpinner.setEnabled(false);
        lessSpinner.setName("lessSpinner"); // NOI18N

        wellSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        wellSpinner.setEnabled(false);
        wellSpinner.setName("wellSpinner"); // NOI18N

        jLabel1.setText("От");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("до");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(betweenRadioButton)
                    .addComponent(moreRadioButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lessRadioButton)
                            .addComponent(wellRadioButton))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wellSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(lessSpinner)
                            .addComponent(moreSpinner)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBetweenSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eBetweenSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(betweenRadioButton)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBetweenSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(eBetweenSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moreRadioButton)
                    .addComponent(moreSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lessRadioButton)
                    .addComponent(lessSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wellRadioButton)
                    .addComponent(wellSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void selectVariant() {
        bBetweenSpinner.setEnabled(betweenRadioButton.isSelected());
        eBetweenSpinner.setEnabled(betweenRadioButton.isSelected());
        moreSpinner.setEnabled(moreRadioButton.isSelected());
        lessSpinner.setEnabled(lessRadioButton.isSelected());
        wellSpinner.setEnabled(wellRadioButton.isSelected());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bBetweenSpinner;
    private javax.swing.JRadioButton betweenRadioButton;
    private javax.swing.JSpinner eBetweenSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton lessRadioButton;
    private javax.swing.JSpinner lessSpinner;
    private javax.swing.JRadioButton moreRadioButton;
    private javax.swing.JSpinner moreSpinner;
    private javax.swing.ButtonGroup qvariantButtonGroup;
    private javax.swing.JRadioButton wellRadioButton;
    private javax.swing.JSpinner wellSpinner;
    // End of variables declaration//GEN-END:variables

    /**
     * Процедура проверки
     * @return
     */
    public boolean checkPanel() {
        try {
            bBetweenSpinner.commitEdit();
            eBetweenSpinner.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(TTRProductsQuantitysDPanel.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(this, "Неправильное значение", "Внимание...", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            moreSpinner.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(TTRProductsQuantitysDPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Неправильное значение", "Внимание...", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            lessSpinner.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(TTRProductsQuantitysDPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Неправильное значение", "Внимание...", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            wellSpinner.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(TTRProductsQuantitysDPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Неправильное значение", "Внимание...", JOptionPane.WARNING_MESSAGE);
            return false;
        }


        if (betweenRadioButton.isSelected()
                && (((Double) bBetweenSpinner.getValue()) > ((Double) eBetweenSpinner.getValue()))) {
            JOptionPane.showMessageDialog(this, "Значение начала диапазона не может "
                    + "\nбыть больше значения конца диапазона.", "Внимание...", JOptionPane.WARNING_MESSAGE);
            return false;
        }



        return true;
    }

    /**
     * Действие при открытии диалога
     */
    public void openPanel() {
    }

    public static void main(String[] args) {
        TTRProductsQuantitysDPanel p = new TTRProductsQuantitysDPanel();
        AUniversalDialog d = new AUniversalDialog(p, null, true);
        d.setVisible(true);
        d.dispose();

        if (d.getReturnStatus() == ADialog.RET_OK) {
        }

    }
}
