/*
 * MoneyOperationAddDPanel.java
 *
 * Created on 5 Март 2008 г., 10:00
 */
package tradeterminal.operations.money;

import java.awt.Dimension;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import minersinstrument.ui.ADialogFocusLisner;
import minersinstrument.ui.IADialogPanel;

/**
 *
 * @author  PKopychenko
 */
public class MoneyOperationAddDPanel extends javax.swing.JPanel implements IADialogPanel {

    /** Creates new form MoneyOperationAddDPanel */
    public MoneyOperationAddDPanel() {
        initComponents();

        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(32, 32));
        jScrollPane1.getHorizontalScrollBar().setPreferredSize(new Dimension(32, 32));


        moneySpinner.setModel(new SpinnerNumberModel(
                Double.valueOf(0.0f),
                Double.valueOf(0.0f),
                Double.valueOf(1000000000),
                Double.valueOf(0.01f)));

        ADialogFocusLisner adf = new ADialogFocusLisner();

        ((JSpinner.DefaultEditor) moneySpinner.getEditor()).getTextField().addFocusListener(adf);
    }

    public String getDescription() {
        return descriptionTextArea.getText();
    }

    public void setDescription(String s) {
        this.descriptionTextArea.setText(s);
    }

    public Object getMoney() {
        return moneySpinner.getValue();
    }

    public void setMoney(Object o) {
        this.moneySpinner.setValue(o);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        moneySpinner = new javax.swing.JSpinner();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(MoneyOperationAddDPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        descriptionTextArea.setRows(5);
        descriptionTextArea.setName("descriptionTextArea"); // NOI18N
        jScrollPane1.setViewportView(descriptionTextArea);

        moneySpinner.setFont(resourceMap.getFont("moneySpinner.font")); // NOI18N
        moneySpinner.setName("moneySpinner"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moneySpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(moneySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean checkPanel() {
        try {

            moneySpinner.commitEdit();
        } catch (ParseException ex) {
            ((JSpinner.DefaultEditor) moneySpinner.getEditor()).getTextField().requestFocus();
        }


        if (((Number) moneySpinner.getValue()).doubleValue() == 0) {
            ((JSpinner.DefaultEditor) moneySpinner.getEditor()).getTextField().requestFocus();

            JOptionPane.showMessageDialog(
                    this,
                    "Введите сумму.",
                    "Информация",
                    JOptionPane.INFORMATION_MESSAGE);

            return false;
        }


        executeSQL();

        return true;
    }

    protected void executeSQL() {
    }

    @Override
    public void openPanel() {
        ((JSpinner.DefaultEditor) moneySpinner.getEditor()).getTextField().requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JSpinner moneySpinner;
    // End of variables declaration//GEN-END:variables
}
