/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OptionsPanel.java
 *
 * Created on 24.02.2011, 19:05:16
 */

package installdb.conf.options_dialogs;

import installdb.conf.AppConstants;
import java.io.File;
import javax.swing.JFileChooser;
import minersinstrument.ui.IADialogPanel;
import minersinstrument.savesettings.csettings.CSettingsTools;
import org.jdesktop.application.Action;

/**
 *
 * @author tt
 */
public class OptionsPanel extends javax.swing.JPanel implements IADialogPanel{

    private JFileChooser fc = new JFileChooser();

    /** Creates new form OptionsPanel */
    public OptionsPanel() {
        initComponents();

        fc.setMultiSelectionEnabled(false);

        pg_dumpPathTextField.setText(CSettingsTools.getStringValue(AppConstants.PG_DUMP_PATH));
        createdbPathTextField.setText(CSettingsTools.getStringValue(AppConstants.CREATEDB_PATH));
        dropdbPathTextField.setText(CSettingsTools.getStringValue(AppConstants.DROPDB_PATH));
        psqlPathTextField.setText(CSettingsTools.getStringValue(AppConstants.PSQL_PATH));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pg_dumpPathTextField = new javax.swing.JTextField();
        createdbPathTextField = new javax.swing.JTextField();
        dropdbPathTextField = new javax.swing.JTextField();
        psqlPathTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(installdb.InstallDBApp.class).getContext().getResourceMap(OptionsPanel.class);
        pg_dumpPathTextField.setText(resourceMap.getString("pg_dumpPathTextField.text")); // NOI18N
        pg_dumpPathTextField.setName("pg_dumpPathTextField"); // NOI18N

        createdbPathTextField.setText(resourceMap.getString("createdbPathTextField.text")); // NOI18N
        createdbPathTextField.setName("createdbPathTextField"); // NOI18N

        dropdbPathTextField.setText(resourceMap.getString("dropdbPathTextField.text")); // NOI18N
        dropdbPathTextField.setName("dropdbPathTextField"); // NOI18N

        psqlPathTextField.setText(resourceMap.getString("psqlPathTextField.text")); // NOI18N
        psqlPathTextField.setName("psqlPathTextField"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(installdb.InstallDBApp.class).getContext().getActionMap(OptionsPanel.class, this);
        jButton1.setAction(actionMap.get("changePgDumpPath")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("changeCreatedbPath")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setAction(actionMap.get("changeDropdbPath")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        jButton4.setAction(actionMap.get("changePsqlPath")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(psqlPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(dropdbPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(createdbPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(pg_dumpPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addComponent(jButton3))
                    .addComponent(jButton4))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pg_dumpPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdbPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdbPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psqlPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton4))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean checkPanel() {

        CSettingsTools.setVal(AppConstants.PG_DUMP_PATH, pg_dumpPathTextField.getText());
        CSettingsTools.setVal(AppConstants.CREATEDB_PATH, createdbPathTextField.getText());
        CSettingsTools.setVal(AppConstants.DROPDB_PATH, dropdbPathTextField.getText());
        CSettingsTools.setVal(AppConstants.PSQL_PATH, psqlPathTextField.getText());

        CSettingsTools.saveCs();
        return true;
    }

    @Override
    public void openPanel() {

    }

    @Action
    public void changePgRestorePath() {
        
    }

    @Action
    public void changePgDumpPath() {
        fc.setSelectedFile(new File(pg_dumpPathTextField.getText()));
        int retVal = fc.showOpenDialog(null);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            pg_dumpPathTextField.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }

    @Action
    public void changeCreatedbPath() {
        fc.setSelectedFile(new File(createdbPathTextField.getText()));
        int retVal = fc.showOpenDialog(null);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            createdbPathTextField.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }

    @Action
    public void changeDropdbPath() {
        fc.setSelectedFile(new File(dropdbPathTextField.getText()));
        int retVal = fc.showOpenDialog(null);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            dropdbPathTextField.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }

    @Action
    public void changePsqlPath() {
        fc.setSelectedFile(new File(psqlPathTextField.getText()));
        int retVal = fc.showOpenDialog(null);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            psqlPathTextField.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField createdbPathTextField;
    private javax.swing.JTextField dropdbPathTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField pg_dumpPathTextField;
    private javax.swing.JTextField psqlPathTextField;
    // End of variables declaration//GEN-END:variables

}
